### ISSUE TITLE
Atividade?

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#1]
Está com zero de atividade por enquanto. Vamos atuar mais, pessoal!

**Comment by drbeco** [comment]
Ninguém respondeu aqui nesta janela sobre atividade. Posso considerar todos inativos?

https://github.com/matheusmoraismoura/wumpusgrp5/issues/1

**Comment by wesleysilas** [comment]
É justamente o que eu lhe informei pelo email professor. Está todo mundo parado. ;/

**Comment by drbeco** [comment]
O seu email foi respondido. Favor postar um NOVO ISSUE com uma proposta de solução.

**Comment by drbeco** [comment]
**ATENÇÃO!! MENSAGEM IMPORTANTE!! ATENÇÃO!!**

-Matheus Morais Moura (*)
-Silas Wesley Maia Marinho (*)
-Gabriel Gouveia (*)
-Priscila de Sousa Silva (*)
-Dennis Miller Fidelis da Silva
-Daniel Henrique Macedo
-Halana Thais Silva Bezerra de Melo
-Wirlany Karla Nascimento Araujo Veloso

---

Caros alunos, o fato de algum de vocês estarem inativos e não terem preocupação maior com a disciplina não significa que não possam ter a especial gentileza de ajudarem os colegas. Então faço a seguinte pergunta:

Quem ainda está ativo e gostaria de mudar para o grupo 4? 

1- Esta pergunta, obviamente, é para ser respondida apenas por quem ainda tem interesse.
2- Quem tem interesse, deve se mostrar ativo, ter boa participação, responder aos bugs com celeridade, e por isso, como este aqui É UM ISSUE (bug), a sua resposta deve ser rápida também.

Dito isso, vou considerar este grupo:
- INATIVO se ninguém responder até amanhã.
- ATIVO se todos responderem (neste caso não há necessidade de mesclar com o grupo 4 e vocês continuam o trabalho aqui no grupo 5. E COMECEM a mostrar atividade e fazer isto de verdade. Como dizem: "pegar o touro pelo chifre")
- DIVIDIDO: se alguns responderem e outros não, até o prazo de amanhã (terça, 24/11/15), meia noite, então os que estão ativos serão movidos para o grupo 4. Os inativos permanecerão aqui. O mesmo eu perguntarei no grupo 4, e os inativos de lá passarão para cá.a

**ATENÇÃO!! MENSAGEM IMPORTANTE!! ATENÇÃO!!**

**Comment by wesleysilas** [comment]
Eu gostaria! Desde já, obrigado professor!!!

**Comment by priscilasousa** [comment]
Boa noite professor, eu gostaria sim, e vou me esforçar mais. Agradeço desde já.

**Comment by gabrielgou** [comment]
Boa noite Professor, eu gostaria sim. 
att,

**Comment by matheusmoraismoura** [comment]
Boa noite professor, tenho interesse. Grato.

**Comment by dmfds** [comment]
Bom dia professor, eu gostaria, vou me mostra mais ativo.

att, Dennis Miller.

Em 23 de novembro de 2015 22:24, Ruben Carlo Benante <
notifications@github.com> escreveu:

**Comment by wesleysilas** [comment]
Como estou vendo, o senhor vai nos deixar no grupo 5 mesmo. 
então, fechando esse issue.

**Comment by drbeco** [comment]
Depois da "reunião" de hoje (não sei se é reunião quando a pessoa está sozinha), eu iria comentar com vocês pessoalmente a conclusão que cheguei:

Cada grupo tem exatamente 4 pessoas. O outro grupo, formado por Francis, Aron, Bruna e Thiago estão batalhando. Eles não tem nenhuma responsabilidade sobre os CINCO (5) que aqui se declararam ativos: Silas, Priscila, Gabriel, Dennis e Matheus.

Vocês inclusive estão em maior número. Não tem sentido eu passar 5 pessoas para que o outro grupo que era só de 4 pessoas passem a ter que organizar reuniões com tanta gente (9 pessoas).

Não, não vou alterar o grupo. Vocês responderam aqui que estão ativos, então mostrem atividade. Se fosse uma ou duas pessoas, pelo tamanho do problema do wumpus, eu poderia mudar. Mas cinco pessoas que até antes de ontem não estavam nem atualizando o git, agora viram a oportunidade de juntar grupos e decidiram se manifestar, então vamos lá, mostrem a atividade que prometeram aqui; Sejam independentes e mostrem o esforço.

E vou falar mais: se apenas dois ou três fizerem, o programa sai. E digo ainda mais, se fosse eu neste grupo, na minha época de estudante, eu não iria ficar me preocupando com ninguém e iria carregar esse grupo nas costas e tirar a melhor nota da turma. E tenho dito!

---

BUG FECHADO.
