### ISSUE TITLE
Salvar as casas seguras.

### ISSUE THREAD

**Issue by gabrielgou** [matheusmoraismoura/wumpusgrp5#10]
Pessoal, temos que fazer uma função que ele va salvando as casa seguras, ou seja, as posição antigas do Agent.
Já foi Implementado a logica para ele saber a Orientação e Casas por onde ele já passou, e Aonde ele está. 
att,

**Comment by wesleysilas** [comment]
Temos que seguir uma lógica como o do "getchar ou scanf" em C. Algo que armazene na memória as casas andadas. Vou pesquisar algo do tipo e falar com paulo. Qualquer resultado, te aviso gabriel!

**Comment by drbeco** [comment]
Atenção para não usar raciocício de programação imperativa (linguagens como C, Java, Python, etc.) e linguagem lógica. Não façam esse tipo de comparação. Programar em PROLOG é outro `paradigma` e você tem que **pensar** diferente.

As casas seguras podem ficar numa lista que vai crescendo conforme outros elementos são inseridos.  E para incluir essa informação como fato dinâmico use `assert` e `retractall`.

**Comment by wesleysilas** [comment]
Eita, obrigado professor!!!

**Comment by gabrielgou** [comment]
Como foi visto a função foi feita mas precisamos trabalhar na seguinte logica, Quando o agente voltar a casas que ele já passou a função continua salvando o que fica desnecessário e repetitivo, 
Imaginem ele salvar a casa [1,1] inicialmente e se por acaso ele passar de novo vai salvar novamente na lista. o que ficaria [[1,1].....[1,1]].

**Comment by gabrielgou** [comment]
corrigido.

**Comment by wesleysilas** [comment]
otimo

**Comment by drbeco** [comment]
Como foi corrigido? Eu tenho uma sugestão para ajudar, mas primeiro gostaria de saber como fizeram.
