### ISSUE TITLE
MOTIVEMO-NOS!!!

### ISSUE THREAD

**Issue by wesleysilas** [matheusmoraismoura/wumpusgrp5#11]
Pessoal, sei que temos nossas inúmeras dificuldades. O fim de período está terrível para todos nós, porém chego ao fim desse dia com uma esperança a mais ao ver que nosso wumpus está se desenvolvendo. Está até mais avançado que os outros grupos- não que isso seja uma competição-. Mas devemos encarar isso como uma injeção de ânimo. Vamos lá!
Gabriel esta aprimorando nossas técnicas em listagem de prolog. 
enfim, Obrigado pela força e pressão professor. 
Vamos lá! :+1:  :+1:

**Comment by priscilasousa** [comment]
Vamos conseguir sim!
