### ISSUE TITLE
adjacentes(Posicao, Lista) 

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#12]
Oi pessoal, queria dar uma sugestão importante.

Poderíamos ter uma função que retornasse as casas adjacentes a casa atual (ou a qualquer casa dada).

Por exemplo, se estou na casa `minhaposicao([2,2])` e chamo:

```
minhaposicao(P),
adjacentes(P, L)
```

Então `L=[[3,2], [2,3], [1,2], [2,1]]`

Ou se estou na posição `[1,1]`, então a lista fica apenas com `L=[[2,1], [1,2]]`

Essa função é uma intermediária para depois ser usada em funções mais complexas.

**Comment by gabrielgou** [comment]
Ok professor, começaremos a implementar essa lógica.
att,

**Comment by wesleysilas** [comment]
Ok professor, valeu pela informação!

**Comment by drbeco** [comment]
Questão:

Se eu tenho uma lista de casas seguras, uma lista de casa adjacentes e uma lista de casas visitadas, e quero calcular uma lista opções de casas para visitar em seguida, quais operações de **conjuntos** eu faço? (União, intersecção, subtração, etc.)?

Suponha:

```
CS = lista de casas seguras
CV = lista de casas visitadas
CA = lista de casas adjacentes
CO = lista de opções de casas para visitar nas próximas rodadas
```

Então a fórmula lógica é?

`CO = ??`

---

Operações `PROLOG` para testar:

```
$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 6.6.6)
Copyright (c) 1990-2013 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- union([[1,1], [2,2]], [[1,1], [3,3]], L).
L = ??

?- list_to_set([[1,1], [2,2], [1,1], [3,3]], L).
L = ??

?- intersection([[1,1], [2,2], [3,3], [2,1]], [[1,1], [2,2], [1,2]], L).
L = ??

?- subtract([[1,1], [2,2], [3,3], [4,4], [2,1]], [[4,4],[2,1],[1,2]], L).
L = ??

?- 
```

Discussão abaixo:

**Comment by gabrielgou** [comment]
entendo que a lista de possíveis casas pra ele na próxima rodada seria Uma intersecção das casas adjacentes com as casas seguras.
E as casas seguras fossem casas adjacentes e a casa atual onde ele não sente nenhuma percepção na casa atual, ou nenhuma brisa/fedor.

**Comment by drbeco** [comment]
Escreva em forma de uma fórmula ou notação matemática (exemplo `-` para subtração, `+` para união e `i` para intersecção). Senão você dilui sua idéia num texto em português. Fica mais claro se for uma simples linha com a fórmula.

**Comment by drbeco** [comment]
Exemplo:

```
-----------------------------------------
|         |     P   |         |       G |
-----------------------------------------
|         |     P   | W       |         |
-----------------------------------------
|         |         |     P   |         |
-----------------------------------------
|         |   A     |         |         |
-----------------------------------------
```

Suponha que o agente já andou por `[1,1]`, `[2,1]` e `[3,1]` e está de volta para a casa `[2,1]` e agora quer calcular uma casa segura e não visitada e adjacente (no caso a resposta é a casa `[2,2]`). Como fazer?

Faça as listas:

```
CS = lista de casas seguras
CV = lista de casas visitadas
CA = lista de casas adjacentes
```

Faça um teste no prompt do PROLOG com a fórmula por você criada:

```
CO = fórmula? Lista resultante?
```

Mostre a fórmula usando as operações acima (intersecção, união, subtração, ou outra operação de lista/conjunto que precisar), mostre o teste feito no `swipl` (direto no prompt).

**Comment by wesleysilas** [comment]
Implementei as casas adjacentes!!!

**Comment by drbeco** [comment]
Coloque aqui para mim a resposta das perguntas que fiz. Espero que o grupo responda, pois estou usando esta questão para avaliar. Escrevam aqui os testes feitos no _prompt_ do PROLOG para justificar sua resposta e a fórmula encontrada.

**Comment by gabrielgou** [comment]
Penso da seguinte forma, ex:
CS = [[1,1], [2,1],[1,2],[2,2],[3,1]]
CV = [[1,1],[2,1],[3,1]]
CA = [[1,1],[2,2],[3,1]]

CO(X):- 
        subtract([[1,1],[2,1],[1,2],[2,2],[3,1]], [[1,1],[2,1],[3,1]], List), 
        intersection(List, [[1,1],[2,2],[3,1]], X).

No caso subtrair as casas seguras das visitadas, que no caso seria List=[[1,2],[2,2]]
e faria a intersecção com as casas adjacentes para saber quais a casa que poderia ir baseado na casa atual, no caso, X=[[2,2]].

**Comment by drbeco** [comment]
Maravilha
