### ISSUE TITLE
Failed miserably

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#15]
## Atualização (master/develop)

A mensagem 
`External function run_agent(Percept, No Action) failed miserably!`
agora mostra qual foi a percepção que o agente recebeu que não soube retornar uma ação.

**Comment by drbeco** [comment]
Por que este bug informativo continua aberto? 

Pessoal, tem que fechar os bugs.

**Comment by gabrielgou** [comment]
ok professor.
