### ISSUE TITLE
Cuidado com (1,1) e [1,1]

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#18]
O predicato:

`assert(casas_seguras(casa(1,1))),`

está criando um fato com dois argumentos `casa\2` enquanto outros usam o modelo `fato\1`, ou seja, um único argumento com uma lista. Por exemplo: `assert(atual_posicao([1,1])),`

Isso vai dar dor de cabeça no futuro. Padronize tudo para usar apenas `fato(_)` , isto é, um argumento.

**Comment by gabrielgou** [comment]
Obrigado professor, foi corrigido.

**Comment by drbeco** [comment]
Gabriel, eu estava falando da **quantidade** de argumentos (usar apenas 1). Você usou uma **variável anônima**.

Acredito que você vai perceber o erro quando o programa não funcionar. Abra outro bug para tratar da substituição de uma **constante** por uma **variável anônima** assim que perceber o erro.

Este bug permanece fechado, pois você acertou a quantidade, apesar de ter confundido os conceitos.

**Comment by drbeco** [comment]
Novidades aqui?

**Comment by wesleysilas** [comment]
várias vezes eu errei nisso aí... 
depois revisei o meu código e saí corrigindo.
valeu professor!
