### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#2]
Todos colaboradores, postar mensagem que estão adicionados.

O último, fechar o bug.

**Comment by drbeco** [comment]
Ninguém respondeu aqui ainda. Qual a desculpa? Não prometeram atividade?

**Comment by matheusmoraismoura** [comment]
Estou adicionado como colaborador, :+1:

**Comment by wesleysilas** [comment]
Todos estão!

**Comment by drbeco** [comment]
## Apenas Matheus e Wesley responderam este bug. 

Bug fechado!!
