### ISSUE TITLE
Fechar milestones atrasadas

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#21]
![image](https://cloud.githubusercontent.com/assets/5805111/11841849/afe94422-a3de-11e5-872c-23aeb71c3135.png)

Não deixe milestones abertas. Ao fechar, não esqueça de fazer release (merge no master com tags).

**Comment by drbeco** [comment]
Novamente o mesmo erro. Milestone v1.0 está atrasado aberto.

**Comment by wesleysilas** [comment]
falta a fechar essa issue e a outra que está atribuída a a versão 1.0
vou lançar ela para 1.1 como o senhor aconselhou.
