### ISSUE TITLE
Caminho de volta

### ISSUE THREAD

**Issue by wesleysilas** [matheusmoraismoura/wumpusgrp5#23]
Estamos tendo um problema que nosso agente até pega o ouro e mata o wumpus, porém ele não volta para a casa inicial.
como implementaríamos uma função pra que ele reconheça as casas seguras para voltar??

**Comment by wesleysilas** [comment]
como o professor explicou hoje na sala..
vou colocar para a versão 1.1, pois a de hoje já foi apresentada, então lancei pra o milestone à frente.

**Comment by gabrielgou** [comment]
O agent já consegue fazer seu caminho de volta a 1,1

**Comment by wesleysilas** [comment]
muito bom! mais um problema resolvido!!!
