### ISSUE TITLE
PDF no github

### ISSUE THREAD

**Issue by wesleysilas** [matheusmoraismoura/wumpusgrp5#25]
Embora seja uma issue sobre um problema não tão grande assim, acho que é uma dúvida não só minha mas de outras pessoas dos outros grupos também...

Profº, Como faço pra pôr o arquivo em PDF aqui no git??? 
desculpe-me a ignorância da pergunta, mas eu não achei como adicionar-lo aqui. :/

**Comment by wesleysilas** [comment]
preciso colocar aqui para a sua avaliação final do dia 20/12

**Comment by drbeco** [comment]
É do mesmo modo que se adiciona qualquer arquivo de qualquer extensão, seja `.c`, `.pl`, `makefile`, `.md` ou `.pdf`. Você coloca o arquivo no repositório no hydra e faz `git add`, etc.

**Comment by drbeco** [comment]
Ah, e por favor, não me atribua bugs. Isso aqui é para vocês discutirem, não para tirar dúvidas. Perguntem uns aos outros, vão nos textos das aulas e no dropbox. Ok?

**Comment by wesleysilas** [comment]
ok. Valeu aí professor e me desculpe por ter lhe marcado! não vai mais se repetir.

**Comment by wesleysilas** [comment]
pronto! o PDF está adicionado... na lista de commits!
