### ISSUE TITLE
Função Traçar Rota

### ISSUE THREAD

**Issue by gabrielgou** [matheusmoraismoura/wumpusgrp5#26]
Foi implementado para o agente seguir pelas casas seguras, porém existe um bug que é ele escolher ir para uma casa que não é adjacente a ele, para isso temos que criar um função para traçar a rota da posição atual até a posição da casa objetivo pelas casas adjacentes, Como visto abaixo:

![sem titulo](https://cloud.githubusercontent.com/assets/14056923/11916304/0db63bea-a6b0-11e5-8caa-389aaef1f6e5.png)

**Comment by wesleysilas** [comment]
vamos tentar até o fim do dia!

**Comment by gabrielgou** [comment]
função desenvolvida, junto com fuga para se CasasVisitadas=CasasSeguras, ou se o agent fizer mais 50 jogadas.

**Comment by wesleysilas** [comment]
valeu dms!
