### ISSUE TITLE
Simulador V.3

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#3]
Cientes que mudou a versão do simulador?

Agora só sorteia 3 buracos!

Use:

`wumpusworld(pit3, 4).`

**Comment by matheusmoraismoura** [comment]
Ok professor, obrigado

**Comment by wesleysilas** [comment]
Tudo bem Professor!

**Comment by gabrielgou** [comment]
Ciente.

**Comment by drbeco** [comment]
*\* ATENÇÃO **

Nova atualização. Coloquei uma definição de módulo, para proteger o simulador de acesso indevido do agente.

A única função externa do simulador é a função `start`, para começar o jogo.

O resto é interna e não deve ser usada. Qualquer dedução sobre o mundo o agente deve fazer por si só, por seus próprios meios (e não consultar o simulador).

Atualizem os seus ramos master e develop (`git pull`).

---

Após lerem aqui, o último fechar o bug.

**Comment by gabrielgou** [comment]
ciente.

**Comment by wesleysilas** [comment]
tudo ok!

**Comment by wesleysilas** [comment]
alterei agora o numero de buracos.
fechando o bug.
