### ISSUE TITLE
Milestones?

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#5]
Os milestones não foram definidos! Isso é tarefa IMEDIATA (já perderam o prazo do primeiro)

**Comment by drbeco** [comment]
Ninguém se prontificou a criar milestones. Qual a desculpa aqui também? Não está sendo por falta de avisos. Repare bem, a gente faz nossas escolhas e tem que aceitar as consequências. Vamos agilizar, pessoal. Vocês tem capacidade!! Acredito em vocês, senão não estaria aqui incentivando!

**Comment by wesleysilas** [comment]
Abri a data de atualização! Milestone!

**Comment by drbeco** [comment]
| N | Data | Milestone | Descrição |
| --- | --- | --- | --- |
| 1 | 17/11/15 | Versão 0.1 | Criar repositório, rascunhos, clones, ramos, add autores |
| 2 | 19/11/15 | Versão 0.2 | Fazer um agente funcional mínimo que passeie pelo labirinto |
| 3 | 26/11/15 | Versão 0.3 | Colocar alguma inteligência no agente |
| 4 | 03/12/15 | Versão 0.4 | Melhorar as respostas dadas para as percepções do agente |
| 5 | 10/12/15 | Versão 0.5 | Lembrar dos caminhos, casas seguras, pegar o ouro com sucesso |
| 6 | 17/12/15 | Versão 1.0 | Buscar a saída através de caminho seguro. Versão Final |
| 7 | 20/12/15 | Versão 1.1 | Versão final após adiamento. |

**Comment by wesleysilas** [comment]
Já introduzi algumas partes da inteligencia do agente.

**Comment by drbeco** [comment]
## REABERTO O BUG!

![image](https://cloud.githubusercontent.com/assets/5805111/11404478/ce485142-9380-11e5-9523-05bc1e03fb56.png)

**Milestones** : só fechar este bug quando criarem as milestones corretas. (conforme tabela acima)

**Comment by drbeco** [comment]
Não existe milestone com nome "data de atualização", e nem milestone com nome de "wiki". Milestones tem nome "Versão xxx" e tem as datas conforme a tabela.

**Comment by wesleysilas** [comment]
Pronto Professor, ajeitei o meu erro.
Posso fechar esse bug agora???
Obrigado!

**Comment by drbeco** [comment]
Vejo que foram criadas as milestones v0.3 e v1.1. Ok!
Crie as outras todas, com as datas mostradas na tabela. (Crie todas, mesmo as que estão atrasadas).

**Comment by wesleysilas** [comment]
Criei todas. Obrigado!
fechando o bug.

**Comment by drbeco** [comment]
Reaberto: todos milestones estão com data incorreta (estão nas quartas, deveriam estar nas quintas) Execeção do primeiro (terça) e do último (doming).

**Comment by matheusmoraismoura** [comment]
Obrigado professor, alterações feitas para as quintas feiras , exceto o primeiro e o ultimo.

**Comment by drbeco** [comment]
Milestone versão 1.1 é dia 20, domingo. CONFORME TABELA.

**reaberto**

**Comment by matheusmoraismoura** [comment]
Alterado, tudo certo agora professor?

**Comment by wesleysilas** [comment]
Desculpe aí pelo erro inicial prof!

**Comment by drbeco** [comment]
Não sei, você me diz. Tem CERTEZA que está tudo certo? Se tiver, fecha o bug de novo.

(Confira a data da versão 1, por favor, conforme a simples tabelinha ali acima)

**Comment by wesleysilas** [comment]
agora sim!

**Comment by drbeco** [comment]
Desisto. Vou desenhar:

![desenho-milestones](https://cloud.githubusercontent.com/assets/5805111/11414754/e358d028-93d7-11e5-8cc7-8021b68b09e2.png)

**Comment by wesleysilas** [comment]
HÁ UM BUG.
No nosso git está aparecendo as datas normais(17/11  17/12   20/12) e no do senhor está assim. 
isso aconteceu com o grupo 1 também! as datas estão loucas!

**Comment by matheusmoraismoura** [comment]
de fato, nossas datas estao de acordo com a primeira imagem que o senhor enviou.

**Comment by drbeco** [comment]
Não tem bug nenhum no github, nem aqui, nem no grupo 1. Lá eles já confirmaram o erro e corrijiram. Aqui continua errado. Faz um print-screen por favor e cola aqui nos comentários.

**Comment by wesleysilas** [comment]
![image](https://cloud.githubusercontent.com/assets/13754136/11449505/920ee200-955f-11e5-8aa6-97a4639c911b.png)

**Comment by wesleysilas** [comment]
essas são a do mês de dezembro que o senhor apontou os problemas nas datas.

**Comment by wesleysilas** [comment]
![image](https://cloud.githubusercontent.com/assets/13754136/11449524/3197fc26-9560-11e5-8089-94841a43eca8.png)

e essa do milestone 0.1. do mês de novembro!
por isso que fechei esse bug algumas vezes, pois desde o início que eu fiz os milestones que aparecem assim! Desculpe aí mais uma vez!

**Comment by drbeco** [comment]
Editei eu mesmo e fechei. Coloquei na descrição a edição.
