### ISSUE TITLE
INATIVIDADE.

### ISSUE THREAD

**Issue by wesleysilas** [matheusmoraismoura/wumpusgrp5#6]
Pessoal, sei que estamos com nossas dificuldades de fim de período, muita correria e aflição, porém, se ficarem parados como estão não vai adiantar de nada. Os únicos que se comunicam sou eu e Matheus Moura. Assim fica difícil.

**Comment by dmfds** [comment]
Bom dia pessoal, concordo com silas. E confesso que estive um pouco ausente, mas a partir de hoje estarei na Poli todas as tardes para contribuir com o trabalho.

**Comment by drbeco** [comment]
Ótimo Silas e Denis! Continuem nos estudos! Lembrem-se:
- 5 commits por dia
- 1 push no develop por dia
- 1 push no master por semana

**Comment by matheusmoraismoura** [comment]
Vamos tentar render alguma coisa!

**Comment by wesleysilas** [comment]
Estamos nos movimentando. 
caro professor, obrigado pelo incentivo.
Queria desde já lhe informar que tenha um pouco de paciência conosco no que tange às metas diárias e semanais. Com toda nossa dificuldade, estamos tentando. Obrigado, 
fechando essa issue. ;)

**Comment by drbeco** [comment]
Commits tem data. Perdeu, perdeu. Não dá para "estudar de véspera" como se faz com a falta de organização de provas. Isso aqui é projeto, não é prova.

Estou acompanhando os commits. No momento existe apenas:

![image](https://cloud.githubusercontent.com/assets/5805111/11403945/3fd4ba9c-937e-11e5-99df-06472ab53d92.png)

**Comment by wesleysilas** [comment]
Mas professor, Estamos nos esforçando mesmo com tanta dificuldade. 
Estamos buscando ajuda sobre o assunto. Pode perguntar ao monitor, estive conversando com ele e tirando dúvidas. Estamos cientes que temos que dar commits, mas antes disso, precisamos saber o que vamos dar. Não estamos estudando de véspera, tem quase um mês ainda. 
obrigado pela compreensão!
