### ISSUE TITLE
Reunião presencial

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#7]
Marcar aqui uma reunião entre vocês (eu não participo, portanto não precisa me perguntar o dia que posso).

Marcar para essa semana, urgente. Preferência hoje ou amanhã (quarta).

Se não puderem, marquem para quinta.

Discutam aqui abaixo neste "forum" sobre suas disponibilidades individuais e cheguem a um consenso.

(Não respondam por "email"! Visitem o site, aprendam a trabalhar com o site: http://github.com/ )

**Comment by matheusmoraismoura** [comment]
A tarde eu trabalho, já que temos algumas aulas vagas amanhã, poderia ser depois da aula de Lucia, ou antes. :+1:

**Comment by gabrielgou** [comment]
Amanha de manhã por mim está ótimo.

**Comment by wesleysilas** [comment]
Estou o dia todo na Poli. 
Por mim, qualquer horário tá bom!

**Comment by drbeco** [comment]
1- Que horas acaba a aula da Profra. Lucia? 2-Onde irão se reunir, por favor?

**Comment by gabrielgou** [comment]
A aula termina de 10:30 Prof, provavelmente iremos para a biblioteca.

**Comment by drbeco** [comment]
Vou dar uma passada aí daqui uns 40 minutos, se estiverem aí ainda.

**Comment by priscilasousa** [comment]
Gente, me desculpem, não poderei estar na reunião hj, pois estou com febre. Mas o que for decidido nesta reunião, estou super de acordo.

**Comment by wesleysilas** [comment]
Infelizmente não ouve uma organização maior para tal reunião presencial.
mas quero deixar claro ao nosso orientador, que tivemos uma reunião e, como o grupo pelo visto vai ser o mesmo, vamos tentar fazer o trabalho, tentar...
Obrigado pelo apoio professor.

**Comment by drbeco** [comment]
A reunião foi um sucesso.

Encontrei sem agendar com ninguém pessoas de todos(*) os grupos reunidos na biblioteca (sala inferior).

Conversei sobre o agente wumpus com os grupos de 1 a 4. Tiramos dúvidas. Comentamos sobre como utilizar assert/retract e outras ferramentas do prolog que recomendo vocês pesquisarem: cut, fail.

Também comentei sobre o novo arquivo PDF no camelobox, pasta de lógica, que é um resumo do PROLOG. Bom olhar lá.

Outras buscas no google podem ajudar, como "tutorial prolog", e "exemplos de listas prolog"

---

Sobre o fato de ninguém do grupo 5 ter aparecido, só tenho a dizer o seguinte: ao encontrar todo mundo  dos outros grupos estudando lá, me veio a clara conclusão: não é necessário agendar, sofrer para conseguir iteragir, ver essa dificuldade toda até para se harmonizar como grupo. É apenas necessário querer. Se vocês quiserem, vocês são tão capazes como quaisquer outros.

---

(*) Exceção do grupo 5 que não encontrei ninguém.
