### ISSUE TITLE
Nossa Wiki.

### ISSUE THREAD

**Issue by wesleysilas** [matheusmoraismoura/wumpusgrp5#8]
Pessoal, 
de acordo com o que sabemos e toda nossa proposta de desenvolvimento, vamos decidir aqui nesse issue como será nossa wiki. 
Quero bem organizada e explicada. Vamos dar ideias. 
no final de tudo, organizarei e finalizarei a wiki.
ideia, please!

**Comment by drbeco** [comment]
Dica importante: sempre que criar um novo "issue", marcar um LABEL e um MILESTONE.

![image](https://cloud.githubusercontent.com/assets/5805111/11403386/56a1d564-937b-11e5-82a4-b736d9495753.png)

**Comment by wesleysilas** [comment]
Valeu pela dica professor! :+1:

**Comment by wesleysilas** [comment]
Pessoal, estou esperando vocês falarem aqui sobre a wiki. 
Priscila? Dennis?

**Comment by priscilasousa** [comment]
Sim Silas, já começamos com a wiki, vamos colocar sobre o que estamos fazendo no trabalho, sobre a linguagem que estamos usando, sobre o curso...

**Comment by drbeco** [comment]
Wiki é opcional e uma boa ideia. Mas Priscila, vc disse que "já" começou? A wiki está vazia:

![image](https://cloud.githubusercontent.com/assets/5805111/11412311/349ff56a-93ba-11e5-9947-cef1915b5d6d.png)

**Comment by wesleysilas** [comment]
kkkkkk agora eu ri! 
Ela deve ter começado com os projetos que orientei ela, Professor. 
Pedi pra ela organizar os temas que vamos expor na wiki. Obrigado! 
kkkk

**Comment by drbeco** [comment]
Ok, pode ser. Mas é melhor fazer a organização (rascunho) direto na própria wiki. É para isso mesmo. É para fazer uma versão ruim, pequena, e ir aumentando. Essa história de tentar fazer upload de tudo pronto e perfeito não dá certo para esse tipo de projeto em que conta o "processo contínuo" de avaliação, e não só a versão final.

Se aparecer com um projeto final "perfeito" mas sem "histórico" de continuidade, de nada vale.

**Comment by wesleysilas** [comment]
Ok, tudo bem!

**Comment by wesleysilas** [comment]
comecarei a nossa wiki!!!
