### ISSUE TITLE
Whastapp não, github sim.

### ISSUE THREAD

**Issue by drbeco** [matheusmoraismoura/wumpusgrp5#9]
Pessoal,

Evitem discutir temas importantes pelo whatsapp, pois a minha avaliação vocês tem que saber, é baseada na atividade pública aqui!

Então abram mais bugs, discutam como solucionar os problemas, trechos de códigos, divisão de trabalhos (ali ao lado tem o botão "assignee" para atribuir um bug específico a uma pessoa, por exemplo), etc.

Força! Bons estudos!

**Comment by priscilasousa** [comment]
desculpe professor, discutiremos sobre o trabalho por aqui. Obg por nos avisar.

**Comment by gabrielgou** [comment]
Obrigado pela dica.

**Comment by wesleysilas** [comment]
Obrigado Professor!

**Comment by wesleysilas** [comment]
PESSOAL, OLHEM O ISSUE DA WIKI. NÃO VI NINGUÉM AINDA LÁ
